### ISSUE TITLE
The chrome extension is not rendering the [stem] part correctly:

### ISSUE THREAD

**Issue by kindlychung** [asciidoctor/asciidoctor-chrome-extension#123]
The chrome extension is not rendering the [stem] part correctly:

![](http://i.imgur.com/0L5bKjH.png)

Link to doc: https://github.com/kindlychung/testGistDoc/blob/master/main.adoc

**Comment by Mogztter** [comment]
Hello @kindlychung,

[MathJax](https://www.mathjax.org/) is using "unsafe-eval" and [GitHub is using a CSP](https://github.com/blog/1477-content-security-policy) to protect you against XSS attacks. In this case Chrome will refuse to evaluate MathJax code.

You can see the following exception in the Chrome DevTools JavaScript console:
```
MathJax.js?config=TeX-MML-AM_HTMLorMML:19 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'none'".
```

I tried to workaround this limitation but so far all my attempts failed... until today! I read (again) https://github.com/mathjax/MathJax/issues/256 and it turns out that I was using inline configuration. I slightly changed my code to use a "static" configuration and now MathJax is working on GitHub. Previously MathJax was only working on local files. I will send a pull request shortly. Thanks for this report :+1:

**Comment by kindlychung** [comment]
Cool! Looking forward to the new version!

**Comment by mojavelinux** [comment]
:+1:
